name: State tests for web app
on: [push, pull_request]

jobs:  
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'

      - name: Install sharedAPI
        working-directory: ./api
        run: npm install --legacy-peer-deps
     
      - name: Install app
        working-directory: ./appv2
        run: npm install
        
      - name: Test
        working-directory: ./appv2
        env:
          MOBILE: false
          JEEPSQLITE: 'FALSE'
          REDIRECT_URI: ''
          IAPP_GEOJSON_URL: ''
          REACT_APP_API_HOST: ''
          SSO_CLIENT_ID: ''
          SSO_REALM: ''
          PUBLIC_MAP_URL: ''
          CONFIGURATION_SOURCE: 'Provided'
          OPENSHIFT_BUILD_COMMIT: ''
          SOURCE_GIT_COMMIT: $GITHUB_SHA   
        run: npm run test
        
